In [1]:
'''Shows plots in Jupyter Notebbok browser.'''
%matplotlib inline

# Load libraries

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sbn
import scipy as sp
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder,LabelBinarizer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.preprocessing import Normalizer
from datetime import datetime
from sklearn import linear_model
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform
from sklearn.model_selection import KFold, cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [3]:
# Set random seed
np.random.seed(0)

# Load Datasets

In [4]:
training_data = pd.read_csv('D:/ML/Project,Standard bank tech influence/Train.csv')
testing_data = pd.read_csv('D:/ML/Project,Standard bank tech influence/Test.csv')
training_data.tail()

CustomerId TransactionStartTime   Value  Amount       TransactionId  \
2095   CustomerId_28  2019-03-30 21:55:11  2000.0 -2000.0  TransactionId_1185   
2096   CustomerId_28  2019-03-30 23:54:07  5000.0 -5000.0  TransactionId_1824   
2097   CustomerId_34  2019-03-31 05:40:10  5000.0 -5000.0  TransactionId_2507   
2098  CustomerId_346  2019-03-31 09:37:19  1500.0 -1500.0   TransactionId_540   
2099  CustomerId_188  2019-03-31 12:16:33  1000.0 -1000.0  TransactionId_1889   

           BatchId    SubscriptionId CurrencyCode  CountryCode    ProviderId  \
2095  BatchId_2069  SubscriptionId_7          UGX          256  ProviderId_1   
2096  BatchId_1552  SubscriptionId_7          UGX          256  ProviderId_1   
2097  BatchId_1093  SubscriptionId_7          UGX          256  ProviderId_1   
2098  BatchId_1239  SubscriptionId_7          UGX          256  ProviderId_1   
2099   BatchId_355  SubscriptionId_7          UGX          256  ProviderId_1   

         ...            LoanId           PaidOnDate IsFinalPayBack  \
2095     ...        LoanId_293  2019-04-29 14:35:17            1.0   
2096     ...       LoanId_1040  2019-04-29 14:32:37            1.0   
2097     ...       LoanId_1585  2019-06-15 06:20:05            1.0   
2098     ...       LoanId_1314  2019-04-23 15:44:15            1.0   
2099     ...       LoanId_1570  2019-04-10 17:33:19            1.0   

        InvestorId              DueDate       LoanApplicationId  \
2095  InvestorId_1  2019-04-29 21:55:06   LoanApplicationId_524   
2096  InvestorId_1  2019-04-29 23:53:57  LoanApplicationId_1441   
2097  InvestorId_1  2019-04-30 05:40:02  LoanApplicationId_1466   
2098  InvestorId_1  2019-04-30 09:37:15  LoanApplicationId_1389   
2099  InvestorId_1  2019-04-30 12:16:26    LoanApplicationId_57   

           PayBackId       ThirdPartyId IsThirdPartyConfirmed  IsDefaulted  
2095  PayBackId_1106   ThirdPartyId_857                   1.0          0.0  
2096   PayBackId_966   ThirdPartyId_958                   1.0          0.0  
2097  PayBackId_1271  ThirdPartyId_1981                   1.0          0.0  
2098   PayBackId_945   ThirdPartyId_705                   1.0          0.0  
2099   PayBackId_830   ThirdPartyId_899                   1.0          0.0  

[5 rows x 27 columns]

In [5]:
testing_data.tail()

CustomerId TransactionStartTime   Value  Amount       TransactionId  \
900  CustomerId_412  2019-07-16 00:18:46   500.0  -500.0   TransactionId_680   
901  CustomerId_326  2019-07-16 03:17:01  1000.0 -1000.0  TransactionId_2504   
902  CustomerId_497  2019-07-16 15:06:22  1000.0 -1000.0   TransactionId_995   
903  CustomerId_497  2019-07-16 15:09:58   800.0  -800.0   TransactionId_708   
904  CustomerId_372  2019-07-17 05:34:45  1900.0 -1900.0   TransactionId_585   

          BatchId    SubscriptionId CurrencyCode  CountryCode    ProviderId  \
900  BatchId_2079  SubscriptionId_7          UGX          256  ProviderId_1   
901  BatchId_1432  SubscriptionId_7          UGX          256  ProviderId_1   
902  BatchId_1410  SubscriptionId_7          UGX          256  ProviderId_1   
903  BatchId_1343  SubscriptionId_7          UGX          256  ProviderId_1   
904   BatchId_665  SubscriptionId_7          UGX          256  ProviderId_1   

       ProductId ProductCategory    ChannelId  TransactionStatus  \
900  ProductId_1         airtime  ChannelId_1                  0   
901  ProductId_7         airtime  ChannelId_1                  0   
902  ProductId_7         airtime  ChannelId_1                  0   
903  ProductId_3         airtime  ChannelId_1                  0   
904  ProductId_7         airtime  ChannelId_1                  0   

    IssuedDateLoan LoanId InvestorId LoanApplicationId ThirdPartyId  
900            NaN    NaN        NaN               NaN          NaN  
901            NaN    NaN        NaN               NaN          NaN  
902            NaN    NaN        NaN               NaN          NaN  
903            NaN    NaN        NaN               NaN          NaN  
904            NaN    NaN        NaN               NaN          NaN

# Setting ID as index

In [6]:
training_data.set_index('CustomerId', inplace = True)
testing_data.set_index('CustomerId', inplace = True)

In [7]:
testing_data.head()

TransactionStartTime    Value   Amount       TransactionId  \
CustomerId                                                                  
CustomerId_310  2019-03-31 13:33:05  14000.0 -14000.0   TransactionId_925   
CustomerId_243  2019-03-31 15:04:09   1000.0  -1000.0  TransactionId_1080   
CustomerId_142  2019-03-31 17:31:11   2500.0  -2500.0  TransactionId_2315   
CustomerId_142  2019-03-31 17:32:15    500.0   -500.0  TransactionId_1466   
CustomerId_142  2019-03-31 17:34:41   1000.0  -1000.0   TransactionId_337   

                     BatchId    SubscriptionId CurrencyCode  CountryCode  \
CustomerId                                                                 
CustomerId_310  BatchId_1144  SubscriptionId_7          UGX          256   
CustomerId_243  BatchId_1214  SubscriptionId_7          UGX          256   
CustomerId_142  BatchId_2150  SubscriptionId_7          UGX          256   
CustomerId_142  BatchId_1071  SubscriptionId_7          UGX          256   
CustomerId_142  BatchId_2477  SubscriptionId_7          UGX          256   

                  ProviderId    ProductId ProductCategory    ChannelId  \
CustomerId                                                               
CustomerId_310  ProviderId_1  ProductId_7         airtime  ChannelId_1   
CustomerId_243  ProviderId_1  ProductId_8    data_bundles  ChannelId_1   
CustomerId_142  ProviderId_1  ProductId_7         airtime  ChannelId_1   
CustomerId_142  ProviderId_1  ProductId_7         airtime  ChannelId_1   
CustomerId_142  ProviderId_1  ProductId_7         airtime  ChannelId_1   

                TransactionStatus       IssuedDateLoan       LoanId  \
CustomerId                                                            
CustomerId_310                  1  2019-03-31 13:33:04  LoanId_1027   
CustomerId_243                  1  2019-03-31 15:04:08   LoanId_768   
CustomerId_142                  1  2019-03-31 17:31:09  LoanId_1067   
CustomerId_142                  1  2019-03-31 17:32:14   LoanId_202   
CustomerId_142                  1  2019-03-31 17:34:40   LoanId_533   

                  InvestorId       LoanApplicationId       ThirdPartyId  
CustomerId                                                               
CustomerId_310  InvestorId_1   LoanApplicationId_825  ThirdPartyId_1175  
CustomerId_243  InvestorId_1    LoanApplicationId_68   ThirdPartyId_604  
CustomerId_142  InvestorId_1  LoanApplicationId_1223  ThirdPartyId_1521  
CustomerId_142  InvestorId_1   LoanApplicationId_633   ThirdPartyId_406  
CustomerId_142  InvestorId_1   LoanApplicationId_309   ThirdPartyId_302

In [8]:
training_data.tail()

TransactionStartTime   Value  Amount       TransactionId  \
CustomerId                                                                
CustomerId_28   2019-03-30 21:55:11  2000.0 -2000.0  TransactionId_1185   
CustomerId_28   2019-03-30 23:54:07  5000.0 -5000.0  TransactionId_1824   
CustomerId_34   2019-03-31 05:40:10  5000.0 -5000.0  TransactionId_2507   
CustomerId_346  2019-03-31 09:37:19  1500.0 -1500.0   TransactionId_540   
CustomerId_188  2019-03-31 12:16:33  1000.0 -1000.0  TransactionId_1889   

                     BatchId    SubscriptionId CurrencyCode  CountryCode  \
CustomerId                                                                 
CustomerId_28   BatchId_2069  SubscriptionId_7          UGX          256   
CustomerId_28   BatchId_1552  SubscriptionId_7          UGX          256   
CustomerId_34   BatchId_1093  SubscriptionId_7          UGX          256   
CustomerId_346  BatchId_1239  SubscriptionId_7          UGX          256   
CustomerId_188   BatchId_355  SubscriptionId_7          UGX          256   

                  ProviderId    ProductId     ...           LoanId  \
CustomerId                                    ...                    
CustomerId_28   ProviderId_1  ProductId_8     ...       LoanId_293   
CustomerId_28   ProviderId_1  ProductId_7     ...      LoanId_1040   
CustomerId_34   ProviderId_1  ProductId_3     ...      LoanId_1585   
CustomerId_346  ProviderId_1  ProductId_8     ...      LoanId_1314   
CustomerId_188  ProviderId_1  ProductId_3     ...      LoanId_1570   

                         PaidOnDate  IsFinalPayBack    InvestorId  \
CustomerId                                                          
CustomerId_28   2019-04-29 14:35:17             1.0  InvestorId_1   
CustomerId_28   2019-04-29 14:32:37             1.0  InvestorId_1   
CustomerId_34   2019-06-15 06:20:05             1.0  InvestorId_1   
CustomerId_346  2019-04-23 15:44:15             1.0  InvestorId_1   
CustomerId_188  2019-04-10 17:33:19             1.0  InvestorId_1   

                            DueDate       LoanApplicationId       PayBackId  \
CustomerId                                                                    
CustomerId_28   2019-04-29 21:55:06   LoanApplicationId_524  PayBackId_1106   
CustomerId_28   2019-04-29 23:53:57  LoanApplicationId_1441   PayBackId_966   
CustomerId_34   2019-04-30 05:40:02  LoanApplicationId_1466  PayBackId_1271   
CustomerId_346  2019-04-30 09:37:15  LoanApplicationId_1389   PayBackId_945   
CustomerId_188  2019-04-30 12:16:26    LoanApplicationId_57   PayBackId_830   

                     ThirdPartyId  IsThirdPartyConfirmed IsDefaulted  
CustomerId                                                            
CustomerId_28    ThirdPartyId_857                    1.0         0.0  
CustomerId_28    ThirdPartyId_958                    1.0         0.0  
CustomerId_34   ThirdPartyId_1981                    1.0         0.0  
CustomerId_346   ThirdPartyId_705                    1.0         0.0  
CustomerId_188   ThirdPartyId_899                    1.0         0.0  

[5 rows x 26 columns]

# Data Wrangling

creating two new features based on time

In [9]:
# load period in days
LoanPeriod = pd.Series(delta.days for delta in(pd.to_datetime(training_data['DueDate']) - pd.to_datetime(training_data['IssuedDateLoan'])))

In [10]:
# Loan payment Period in day
PaidTime =  pd.Series(delta.days for delta in(pd.to_datetime(training_data['PaidOnDate']) - pd.to_datetime(training_data['IssuedDateLoan'])))

In [11]:
# Adding the new features in the dataset
training_data.insert(25,'LoanPeriod',LoanPeriod.values)
training_data.insert(26,'PaidTime',PaidTime.values)
training_data.head()

TransactionStartTime   Value  Amount       TransactionId  \
CustomerId                                                               
CustomerId_27  2018-09-21 12:17:39   550.0  -550.0  TransactionId_1683   
CustomerId_27  2018-09-25 09:20:29   550.0  -550.0  TransactionId_2235   
CustomerId_27  2018-09-25 10:33:31   550.0  -550.0  TransactionId_1053   
CustomerId_27  2018-09-27 10:26:41  1000.0 -1000.0  TransactionId_2633   
CustomerId_27  2018-09-27 12:44:21   500.0  -500.0    TransactionId_71   

                    BatchId    SubscriptionId CurrencyCode  CountryCode  \
CustomerId                                                                
CustomerId_27   BatchId_641  SubscriptionId_2          UGX          256   
CustomerId_27   BatchId_820  SubscriptionId_2          UGX          256   
CustomerId_27   BatchId_210  SubscriptionId_4          UGX          256   
CustomerId_27   BatchId_876  SubscriptionId_4          UGX          256   
CustomerId_27  BatchId_1362  SubscriptionId_4          UGX          256   

                 ProviderId    ProductId     ...     IsFinalPayBack  \
CustomerId                                   ...                      
CustomerId_27  ProviderId_1  ProductId_7     ...                NaN   
CustomerId_27  ProviderId_1  ProductId_7     ...                NaN   
CustomerId_27  ProviderId_1  ProductId_7     ...                NaN   
CustomerId_27  ProviderId_1  ProductId_7     ...                NaN   
CustomerId_27  ProviderId_1  ProductId_7     ...                NaN   

              InvestorId  DueDate LoanApplicationId  PayBackId ThirdPartyId  \
CustomerId                                                                    
CustomerId_27        NaN      NaN               NaN        NaN          NaN   
CustomerId_27        NaN      NaN               NaN        NaN          NaN   
CustomerId_27        NaN      NaN               NaN        NaN          NaN   
CustomerId_27        NaN      NaN               NaN        NaN          NaN   
CustomerId_27        NaN      NaN               NaN        NaN          NaN   

              IsThirdPartyConfirmed LoanPeriod  PaidTime IsDefaulted  
CustomerId                                                            
CustomerId_27                   NaN        NaN       NaN         NaN  
CustomerId_27                   NaN        NaN       NaN         NaN  
CustomerId_27                   NaN        NaN       NaN         NaN  
CustomerId_27                   NaN        NaN       NaN         NaN  
CustomerId_27                   NaN        NaN       NaN         NaN  

[5 rows x 28 columns]

In [12]:
training_data.shape

(2100, 28)

Handling Missing Values, That is Customers who did not apply for a Loan

In [13]:
training_data.dropna(inplace = True)

Handling Categorical data

In [14]:
label_encoder = LabelEncoder()

In [15]:
# Categorical boolean mask
categorical_feature_mask = training_data.dtypes == object
categorical_cols = training_data.columns[categorical_feature_mask].tolist()

In [16]:
categorical_cols

['TransactionStartTime',
 'TransactionId',
 'BatchId',
 'SubscriptionId',
 'CurrencyCode',
 'ProviderId',
 'ProductId',
 'ProductCategory',
 'ChannelId',
 'IssuedDateLoan',
 'Currency',
 'LoanId',
 'PaidOnDate',
 'InvestorId',
 'DueDate',
 'LoanApplicationId',
 'PayBackId',
 'ThirdPartyId']

In [17]:
training_data[categorical_cols] = training_data[categorical_cols].apply(lambda col: label_encoder.fit_transform(col))

In [18]:
training_data.head()

TransactionStartTime   Value  Amount  TransactionId  BatchId  \
CustomerId                                                                     
CustomerId_233                     0  5000.0 -5000.0            792      998   
CustomerId_305                     1   500.0  -500.0            148      478   
CustomerId_27                      2  1000.0 -1000.0            185      312   
CustomerId_27                      3   500.0  -500.0           1091      692   
CustomerId_27                      4   500.0  -500.0             12      257   

                SubscriptionId  CurrencyCode  CountryCode  ProviderId  \
CustomerId                                                              
CustomerId_233               1             0          256           0   
CustomerId_305               0             0          256           0   
CustomerId_27                0             0          256           0   
CustomerId_27                0             0          256           0   
CustomerId_27                0             0          256           0   

                ProductId     ...       IsFinalPayBack  InvestorId  DueDate  \
CustomerId                    ...                                             
CustomerId_233         12     ...                  1.0           2        0   
CustomerId_305         12     ...                  1.0           1        1   
CustomerId_27          12     ...                  1.0           1        2   
CustomerId_27          12     ...                  1.0           1        3   
CustomerId_27           9     ...                  1.0           1        4   

                LoanApplicationId  PayBackId  ThirdPartyId  \
CustomerId                                                   
CustomerId_233                493        572            10   
CustomerId_305                276       1274           477   
CustomerId_27                 133         67           225   
CustomerId_27                 922       1304           801   
CustomerId_27                 779        175           841   

                IsThirdPartyConfirmed  LoanPeriod  PaidTime  IsDefaulted  
CustomerId                                                                
CustomerId_233                    0.0        29.0       7.0          0.0  
CustomerId_305                    0.0        29.0       0.0          0.0  
CustomerId_27                     0.0        29.0       0.0          0.0  
CustomerId_27                     0.0        29.0       0.0          0.0  
CustomerId_27                     0.0        29.0       0.0          0.0  

[5 rows x 28 columns]

In [19]:
Feature_data = training_data.iloc[:,:-1].values
Target_data = training_data.iloc[:,-1].values
Feature_data.shape

(1479, 27)

In [20]:
Target_data.shape

(1479,)

In [21]:
# Standardize the feature matrix
scaler = StandardScaler()
Feature_data = scaler.fit_transform(Feature_data)
Feature_data

array([[-1.84951685, -0.28156918,  0.28088536, ..., -8.3323809 ,
         0.        , -0.57247399],
       [-1.8464851 , -0.30844424,  0.30775825, ..., -8.3323809 ,
         0.        , -0.79033186],
       [-1.84345335, -0.30545812,  0.30477237, ..., -8.3323809 ,
         0.        , -0.79033186],
       ...,
       [ 1.6248681 , -0.28156918,  0.28088536, ...,  0.12001372,
         0.        ,  1.57498212],
       [ 1.62789985, -0.302472  ,  0.3017865 , ...,  0.12001372,
         0.        , -0.07451316],
       [ 1.6309316 , -0.30545812,  0.30477237, ...,  0.12001372,
         0.        , -0.47910634]])

Dimensionality reduction uding PCA

In [22]:
# Create a PCA that will retain 99% of variance
pca = PCA(n_components=0.99, whiten=True)
# Conduct PCA
Feature_pca = pca.fit_transform(Feature_data)
print(Feature_data.shape)
Feature_pca.shape

(1479, 27)


(1479, 15)

In [23]:
Feature_pca[1]

array([-1.1073199 ,  2.67078076, -2.48557929,  3.69230721, -2.07222403,
        2.75158791, -0.33620907,  2.14747354, -1.32048126,  0.55365247,
        2.41933612,  3.39828625, -3.8891407 , -1.30830043, -0.60970135])

In [24]:
Feature_data[1]

array([-1.8464851 , -0.30844424,  0.30775825, -1.24386011, -0.27796616,
       -2.81210595,  0.        ,  0.        ,  0.        ,  1.08367753,
       -0.64825074,  0.        ,  0.        , -1.84954655, -0.14466974,
        0.        , -0.32397392, -1.73247309,  0.60781942,  1.60121441,
       -1.84969481, -0.92628867,  1.26095747, -0.60595684, -8.3323809 ,
        0.        , -0.79033186])

# Model Selection

Selecting Best Models Using Randomized Search

In [25]:
# Create logistic regression
logistic = linear_model.LogisticRegression()
# Create range of candidate regularization penalty hyperparameter values
penalty = ['l1', 'l2']
# Create distribution of candidate regularization hyperparameter values
C = uniform(loc=0, scale=4)
# Create hyperparameter options
hyperparameters = dict(C=C, penalty=penalty)
# Create randomized search
randomizedsearch = RandomizedSearchCV(
logistic, hyperparameters, random_state=1, n_iter=100, cv=5, verbose=0,
n_jobs=-1)
# Fit randomized search
best_model = randomizedsearch.fit(Feature_pca, Target_data)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [26]:
best_model

RandomizedSearchCV(cv=5, error_score='raise-deprecating',
          estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False),
          fit_params=None, iid='warn', n_iter=100, n_jobs=-1,
          param_distributions={'C': <scipy.stats._distn_infrastructure.rv_frozen object at 0x00000185BB62EA90>, 'penalty': ['l1', 'l2']},
          pre_dispatch='2*n_jobs', random_state=1, refit=True,
          return_train_score='warn', scoring=None, verbose=0)

In [27]:
# Define a uniform distribution between 0 and 4, sample 10 values
uniform(loc=0, scale=4).rvs(10)

array([2.37137847, 3.37706299, 3.43178247, 3.38900696, 2.49425479,
       1.53752683, 1.19013843, 0.22685191, 1.09062518, 1.91066047])

In [28]:
# View best hyperparameters
print('Best Penalty:', best_model.best_estimator_.get_params()['penalty'])
print('Best C:', best_model.best_estimator_.get_params()['C'])

Best Penalty: l2
Best C: 0.40933771531130336


In [29]:
# Predict target vector
best_model.predict(Feature_pca)

array([0., 0., 0., ..., 0., 0., 0.])

Selecting Best Models Using Exhaustive Search

In [30]:
# Create range of candidate regularization hyperparameter values
C = np.logspace(0, 4, 10)
# Create dictionary hyperparameter candidates
hyperparameters = dict(C=C, penalty=penalty)
# Create grid search
gridsearch = GridSearchCV(logistic, hyperparameters, cv=5, verbose=0)
# Fit grid search
best_model = gridsearch.fit(Feature_pca, Target_data)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warni

C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", C

C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", C

In [31]:
# View best hyperparameters
print('Best Penalty:', best_model.best_estimator_.get_params()['penalty'])
print('Best C:', best_model.best_estimator_.get_params()['C'])
np.logspace(0, 4, 10)

Best Penalty: l1
Best C: 166.81005372000593


array([1.00000000e+00, 2.78255940e+00, 7.74263683e+00, 2.15443469e+01,
       5.99484250e+01, 1.66810054e+02, 4.64158883e+02, 1.29154967e+03,
       3.59381366e+03, 1.00000000e+04])

In [32]:
# Predict target vector
best_model.predict(Feature_pca)

array([1., 0., 0., ..., 0., 0., 0.])

# Model Evaluation

Cross-Validating Models

In [33]:
# Create k-Fold cross-validation
kf = KFold(n_splits=10, shuffle=True, random_state=1)

In [34]:
# Create a pipeline that standardizes, then runs logistic regression
pipeline = make_pipeline(scaler, logistic)

In [35]:
# Conduct k-fold cross-validation
cv_results = cross_val_score(pipeline, # Pipeline
Feature_pca, # Feature matrix
Target_data, # Target vector
cv=kf, # Cross-validation technique
scoring="accuracy", # Loss function
n_jobs=-1) # Use all CPU scores

In [36]:
# Calculate mean
cv_results.mean()

0.9337562051847768

In [37]:
cv_results

array([0.94594595, 0.91216216, 0.89864865, 0.87837838, 0.96621622,
       0.9527027 , 0.93243243, 0.93918919, 0.9527027 , 0.95918367])